export const pets = [
    {
        id: 1,
        img:'img/card1.png',
        name: 'Тоня',
        age: '1 год',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 2,
        img:'img/card2.png',
        name: 'Милка',
        age: '5 лет',
        sex: 'Девочка',
        animal: 'кошка',
    },
    {
        id: 3,
        img:'img/card3.png',
        name: 'Буба',
        age: '4 года',
        sex: 'Мальчик',
        animal: 'кошка',
    },
    {
        id: 4,
        img:'img/card4.png',
        name: 'Мари',
        age: '3 года',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 5,
        img:'img/card5.png',
        name: 'Тимка',
        age: '2 года',
        sex: 'Мальчик',
        animal: 'кошка',
    },
    {
        id: 6,
        img:'img/card6.png',
        name: 'Дейзи',
        age: '2 года',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 7,
        img:'img/card7.png',
        name: 'Пушинка',
        age: '4 года',
        sex: 'Девочка',
        animal: 'кошка',
    },
    {
        id: 8,
        img:'img/card8.png',
        name: 'Стрелка',
        age: '6 месяцев',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 9,
        img:'img/card9.png',
        name: 'Рыжик',
        age: '5 лет',
        sex: 'Мальчик',
        animal: 'кошка',
    },
    {
        id: 10,
        img:'img/card10.png',
        name: 'Лёва',
        age: '4 месяца',
        sex: 'Мальчик',
        animal: 'кошка',
    },
    {
        id: 11,
        img:'img/card11.png',
        name: 'Мишка',
        age: '3 года',
        sex: 'Мальчик',
        animal: 'собака',
    },
    {
        id: 12,
        img:'img/card12.png',
        name: 'Найда',
        age: '7 лет',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 13,
        img:'img/card13.png',
        name: 'Лаванда',
        age: '4 года',
        sex: 'Девочка',
        animal: 'кошка',
    },
    {
        id: 14,
        img:'img/card14.png',
        name: 'Вишня',
        age: '5 лет',
        sex: 'Девочка',
        animal: 'кошка',
    },
    {
        id: 15,
        img:'img/card15.png',
        name: 'Алекс',
        age: '3 года',
        sex: 'Мальчик',
        animal: 'собака',
    },
    {
        id: 16,
        img:'img/card16.png',
        name: 'Бусинка',
        age: '4 месяца',
        sex: 'Девочка',
        animal: 'собака',
    },
    {
        id: 17,
        img:'img/card17.png',
        name: 'Кокос',
        age: '3 года',
        sex: 'Мальчик',
        animal: 'кошка',
    },
    {
        id: 18,
        img:'img/card18.png',
        name: 'Альфа',
        age: '7 лет',
        sex: 'Девочка',
        animal: 'собака',
    },

]